name: Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Install Packages
        working-directory: ./pulumi
        run: npm install
      - name: Update
        uses: pulumi/actions@v6
        with:
          work-dir: ./pulumi
          command: up
          stack-name: prod
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
