name: Preview
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x
      - name: Restore Tools & Dependencies
        working-directory: ./app
        run: |
          dotnet tool restore
          dotnet paket restore
      - name: Run Tests
        working-directory: ./app
        run: dotnet run --project src/Tests/Tests.fsproj
  preview:
    name: Preview
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: gke-gcloud-auth-plugin
      - name: Install Packages
        working-directory: ./pulumi
        run: npm install
      - name: TypeScript Check
        working-directory: ./pulumi
        run: npm run check
      - name: Authenticate Pulumi
        uses: pulumi/auth-actions@v1
        with:
          organization: meiermade
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:meiermade
      - name: Preview
        uses: pulumi/actions@v6
        with:
          work-dir: ./pulumi
          command: preview
          stack-name: prod
          diff: true
          comment-on-pr: true
